### ISSUE TITLE
`ModuleNotFoundError: No module named 'synapse.synapse_rust'`

### ISSUE THREAD

**Issue by Hywan** [michaelkaye/setup-matrix-synapse#95]
Hey :-),

We are using this action as follows:

```yaml
      - uses: michaelkaye/setup-matrix-synapse@main
        with:
          installer: poetry
          uploadLogs: true
          httpPort: 8228
          disableRateLimiting: true
```

and it fails with `ModuleNotFoundError: No module named 'synapse.synapse_rust'`, as you can see here https://github.com/matrix-org/matrix-rust-sdk/actions/runs/5923815924/job/16060163847?pr=2428#step:7:209.

Any idea why?
